<a href="https://colab.research.google.com/github/rishabhprasad2003/.ipynb-notebooks/blob/main/D4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
a=0
while(a<10):
  print(a,end=' ')
  a=a+1
  

0 1 2 3 4 5 6 7 8 9 

In [ ]:
import numpy as np
b=np.array([1,2,3,4,5])
b


array([1, 2, 3, 4, 5])

In [ ]:
b.shape
# (column , rows(if 1 then null is represented))

(5,)

In [ ]:
b.ndim # in 1-D array its (column, rows)

1

In [ ]:
c=np.array([[1,2,3],[4,5,6]]) # matrix - 2 dimension
c     # in 2-D , its (rows , column)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
c.size

6

In [ ]:
c.shape  #2 rows and 3 column


(2, 3)

In [ ]:
c.ndim

2

In [ ]:
#np - numpy
#random- package (collection of libraries)
#randint - library
np.random.seed(0) # to keep generted values constant 
d= np.random.randint(0,10,10) # for random integers in range of 1 to 10,
d

array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])

In [ ]:
d.size

10

In [ ]:
d.shape

(10,)

In [ ]:
d=d.reshape(5,2)

In [ ]:
d


array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

In [ ]:
d.reshape(2,5)

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [ ]:
x=np.ones(10) # np.ones is for WHITE COLOR.
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
y=np.zeros(99) # np.zeros is for BLACK COLOR.
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#in numpy range is form (0,255)
# 0 - Black
# 255 - White
# 100 - more of a black than white

In [ ]:
# BGR - (0,255,0) - Green
# (0,0,255) - Red